export const RESPONSE_CODE = {
  SUCCESS_CODE: 200,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  NOT_FOUND: 404,
  TOKEN_EXPIRED: 419,
  FORBIDDEN: 403,
  INVALID_INPUT: 422,
  INTERNAL_SERVER_ERROR: 500,
};

export const CONSTANT_MSG = {
  AUTH: 'Auth',
  INVALID_CREDENTIALS: 'Invalid Credentails',
  DB_ERROR: 'Error in Database Query',
  INVALID_MOBILE_NO: 'Invalid mobile Number',
  UPDATE_FAILED: 'Updation Failed',
  OPTION_DELETED: 'Option deleted successfully',
  OPTION_DELETE_Failed: 'Option deleted failed',
  UPDATE_OK: 'Updated Successfully',
  FETCH_OK: 'Fetched Successfully',
  FETCH_Fail: 'Fetched Failed',
  ALREADY_PRESENT: 'User already present.Do login',
  INVALID_REQUEST: 'Invalid request',
  NO_PERMISSION: 'There is no permission of this action',
  NO_DATA_FOUND: 'No Data Found',
  LOGIN_SUCCESS: 'Login Successfully',
  RESERVATION_LIST: 'Reservation fetched successfully',
  SRU_DETAILS: 'SRU details fetched successfully',
  ODP_DETAILS: 'ODP details fetched successfully',
  NOTIFICATIOM_DETAILS: 'Notification details fetched successfully',
  SIGNATURE_DETAILS: 'Signature details fetched successfully',
  INVALID_USER_PASSWORD: 'Username or Password is Invalid',
  UPDATED_REFRESH_TOKEN: 'Refresh Token Updated Successfully',
  REFRESH_TOKEN_FAILED: 'Refresh Token updation Failed',
  CREATE_OK: 'Created Successfully',
  PROGRAMEE_LIST: 'List of properties fetched successfully',
  PROGRAMEE_LIST_ERROR: 'List of properties fetched failed',
  AGENCY_EMAIL_MISSING: 'Agency email is required',
  PROGRAMEE_ID_MISSING: 'Property ID is required',
  LOT_ID_MISSING: 'Lot ID is required',
  AGENCY_ID_MISSING: 'Agency ID is required',
  Task_MISSING: 'Task is required',
  PROGRAMEE_DETAIL: 'Property detail fetched successfully',
  PROGRAMEE_DETAIL_ERROR: 'Property detail fetched failed',
  EMAIL_NOT_FOUND: 'Please provide email',
  PASSWORD_NOT_FOUND: 'Please provide password',
  USER_NOT_FOUND: 'Login user not found, please check your email and password',
  PAGE_SIZE_MIN: 5,
  PAGE_SIZE_MAX: 10,
  LOT_LIST_ERROR: 'List of lots fetched failed',
  LOT_LIST: 'List of lots fetched successfully',
  PACKAGE_LIST_ERROR: 'List of packages fetched failed',
  PACKAGE_ID_MISSING: 'Package ID is required',
  DELETE_OK: 'Deleted successfully',
  DELETE_FAILED: 'Deleted Failed',
  PACKAGE_LIST: 'List of packages fetched successfully',
  CREATED_OK: 'Created successfully',
  CREATE_FAILED: 'Created failed',
  VALIDATION_FAILED: 'Validation failed',
  DETAIL_SUCCESS: 'Sucessfully fetched detail',
  DETAIL_FAILED: 'Sucessfully fetched detail',
  LIST_OK: 'Sucessfully fetched the list',
  FIREBASE_UPDATE_SUCCESS: 'updated successfully in firebase',
  FIREBASE_UPDATE_FAILED: 'update failed in firebase',
  LIST_FAILED: 'Failed to fetched the list',
  MISSED_USER_TEMPLATE_ID: 'User and Template Id missing',
  MISSED_USER_ID: 'User Id missing',
  MISSED_TEMPLATE_ID: 'Template Id missing',
  OPP_CREATE_FAILED: 'Oppourtunity creation failed',
  TIMELINE_CREATE_FAILED: 'Timeline creation failed',
  OPTION_LENGTH_EXCEEDED: 'Option length has exceeded',
  AGENCY_NOT_FOUND: 'Agency not found',
  FILE_DETAIL_MISSING: 'File or detail missing',
  UPLOAD_SUCCESS: 'File uploaded successfully',
  UPLOAD_FAILED: 'File uploaded failed',
  EMAIL_ALREADY_EXIST: 'Email already exist',
  EMAIL_TEMPLATE_MISSING: 'Email template has missed',
  CONTACT_ID_MISSING: 'Contact Id ID required',
  ROLE_ID_MISSING: 'Role Id ID required',
  ID_MISSING: 'Primary Id missing',
  AGENCY_ACCESS_DENIED: 'Access Denied to access this agency',
  PROPERTY_ACCESS_DENIED: 'Access Denied to access this property',
  PROPERTY_LOT_ACCESS_DENIED: 'Access Denied to access this property lots',
  LOT_CREATE_ACCESS_DENIED:
    'Access Denied to create this lot under this property',
  PROPERTY_PACKAGE_ACCESS_DENIED: 'Access Denied to access this packages',
  PACKAGE_DELETE_ACCESS_DENIED: 'Access Denied to delete this packages',
  PACKAGE_CREATE_ACCESS_DENIED: 'Access Denied to create this package',
  PACKAGE_UPDATE_ACCESS_DENIED: 'Access Denied to update this package',
  PACKAGE_NAME_AVAILABLE: 'Package name already available',
  NAME_PRESENT_ALREADY: 'Name already present',
  PROPERTY_ALREADY_PRESENT: 'Property name already present',
};
